#!/usr/bin/env python3
"""
Invariant assertions for .github/workflows/release.yml.

Run from repo root:
    python3 scripts/validate-release-workflow.py

Exits non-zero on first violated invariant. Designed to catch accidental
regressions of release-pipeline hardening that has bitten us before.

Tracked invariants:
  1. The "Staple" step must NOT use continue-on-error: true.
     Stapling is a release blocker — see commit history for context.
  2. The release job must build & ship CiceroMCP inside Cicero.app.
  3. The Homebrew cask block must declare a `binary` stanza so the
     CiceroMCP binary is symlinked onto PATH as `cicero-mcp`.
  4. secrets.SPARKLE_EDDSA_PUBLIC_KEY must be drift-checked against
     docs/sparkle-public-key.txt at build time.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
WORKFLOW = REPO_ROOT / ".github" / "workflows" / "release.yml"
PUBKEY_FILE = REPO_ROOT / "docs" / "sparkle-public-key.txt"


def fail(msg: str) -> None:
    print(f"INVARIANT VIOLATED: {msg}", file=sys.stderr)
    sys.exit(1)


def load_workflow() -> dict:
    if not WORKFLOW.exists():
        fail(f"workflow not found at {WORKFLOW}")
    with WORKFLOW.open() as f:
        return yaml.safe_load(f)


def find_step(steps: list[dict], name: str) -> dict | None:
    for step in steps:
        if step.get("name") == name:
            return step
    return None


def raw_workflow_text() -> str:
    return WORKFLOW.read_text()


def check_staple_no_continue_on_error(wf: dict) -> None:
    steps = wf["jobs"]["release"]["steps"]
    staple = find_step(steps, "Staple")
    if staple is None:
        fail("expected a 'Staple' step in release job")
    if staple.get("continue-on-error"):
        fail("'Staple' step must not have continue-on-error: true (stapling is a release blocker)")
    # The body must actually fail (exit 1) on exhausted retries.
    body = staple.get("run", "")
    if "exit 1" not in body:
        fail("'Staple' step body must exit 1 when all retries are exhausted")


def check_ciceromcp_bundled(wf: dict) -> None:
    steps = wf["jobs"]["release"]["steps"]
    bundle_step = find_step(steps, "Create .app bundle")
    if bundle_step is None:
        fail("expected 'Create .app bundle' step")
    body = bundle_step.get("run", "")
    if "CiceroMCP" not in body:
        fail("'Create .app bundle' step must copy CiceroMCP into the bundle")
    # We expect a universal build — either single-invocation multi-arch or lipo.
    text = raw_workflow_text()
    has_multiarch_build = "--arch arm64" in text and "--arch x86_64" in text
    has_lipo = "lipo" in text and "CiceroMCP" in text
    if not (has_multiarch_build or has_lipo):
        fail(
            "release workflow must produce a universal CiceroMCP binary "
            "(swift build with --arch arm64 --arch x86_64, or per-arch builds + lipo)"
        )


def check_cask_binary_stanza(wf: dict) -> None:
    steps = wf["jobs"]["release"]["steps"]
    tap_step = find_step(steps, "Update Homebrew tap")
    if tap_step is None:
        fail("expected 'Update Homebrew tap' step")
    body = tap_step.get("run", "")
    # The cask block is generated by a heredoc-ish printf/echo sequence.
    # We assert the binary stanza string appears in the cask generator.
    if "binary " not in body or "CiceroMCP" not in body or "cicero-mcp" not in body:
        fail(
            "Homebrew cask generator must include a `binary` stanza pointing at "
            "Cicero.app/Contents/MacOS/CiceroMCP with target 'cicero-mcp'"
        )


def check_sparkle_key_drift(wf: dict) -> None:
    if not PUBKEY_FILE.exists():
        fail(f"missing committed Sparkle public key at {PUBKEY_FILE}")
    steps = wf["jobs"]["release"]["steps"]
    drift_step = find_step(steps, "Verify Sparkle public key")
    if drift_step is None:
        fail("expected a 'Verify Sparkle public key' step that checks committed key matches secret")
    body = drift_step.get("run", "")
    if "docs/sparkle-public-key.txt" not in body:
        fail("Sparkle public key drift step must read docs/sparkle-public-key.txt")
    if "SPARKLE_EDDSA_PUBLIC_KEY" not in body:
        fail("Sparkle public key drift step must reference the SPARKLE_EDDSA_PUBLIC_KEY secret")


CHECKS = [
    ("staple has no continue-on-error", check_staple_no_continue_on_error),
    ("CiceroMCP bundled into Cicero.app", check_ciceromcp_bundled),
    ("Homebrew cask binary stanza for cicero-mcp", check_cask_binary_stanza),
    ("Sparkle public key drift check", check_sparkle_key_drift),
]


def main() -> None:
    wf = load_workflow()
    for label, fn in CHECKS:
        fn(wf)
        print(f"ok   {label}")
    print("all release-workflow invariants hold")


if __name__ == "__main__":
    main()
